version: 9.0.{build}
os: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  - ps: dotnet restore src/NServiceBus.Persistence.MongoDb.sln
build:
  publish_nuget: true
  verbosity: minimal
services:
  - mongodb
